export const alumniData =
[
  {
    "name": "Sheng Yang",
    "bio":"Postdoc at Northwestern University.",
    "thesis": "On Scheduling and Communication Issues in Data Centers",
    "graduation_date": "Dec. 2020",
    "img": require("../assets/sheng.jpg"),
    "website": "https://www.cs.umd.edu/~styang/",
  },
  {
    "name": "Ioana Bercea",
    "bio":"Postdoc at Tel-Aviv University (Israel).",
    "thesis": "Approximation Algorithms for Touring and Clustering Problems",
    "graduation_date": "July 2018",
    "img": require("../assets/ioana.jpg"),
    "website": "https://ioanabercea.github.io/webpage/",
  },
  {
    "name": "Manish Purohit",
    "bio":"Google Research (Mountain View).",
    "thesis": "Data-Aware Scheduling in Data Centers",
    "graduation_date": "May 2016",
    "img": require("../assets/manish.jpg"),
    "website": "https://sites.google.com/view/manishpurohit/",
  },
  {
    "name": "Kanthi Sarpatwar",
    "bio":"IBM T. J. Watson Research Center.",
    "thesis": "Allocation Algorithms for Networks with Scarce Resouces",
    "graduation_date": "May 2015",
    "img": require("../assets/kanthi.jpg"),
    "website": "https://sites.google.com/view/manishpurohit/",
  },
  {
    "name": "Koyel Mukherjee",
    "bio":"Xerox Research Center India (Bangalore).",
    "thesis": "Algorithmic Approaches to Reducing Resource Costs in Data Centers",
    "graduation_date": "Dec 2013",
    "img": require("../assets/koyel.png"),
    "website": "https://www.linkedin.com/in/koyel-mukherjee-7b47024/?originalSubdomain=in",
  },
  {
    "name": "Jessica Chang",
    "bio":"Dept. of Defense.",
    "thesis": "Energy-Aware Batch Scheduling",
    "graduation_date": "Aug 2013",
    "img": "../assets/uw.png",
    "website": "https://www.linkedin.com/in/jessica-chang-3304ba80/",
  },
  {
    "name": "Saeed Alaei",
    "bio":"First position: Postdoc at Cornell University. Now at Google Research (Mountain View)",
    "thesis": "Mechanism design with general utilities",
    "graduation_date": "Aug 2012",
    "img": "../assets/saeed.jpeg",
    "website": "http://www.cs.cornell.edu/~saeed/",
  },
  {
    "name": "Barna Saha",
    "bio":"First job AT&T Labs. Now at U. Massachussets (Amherst).",
    "thesis": "Approximation Algorithms for Resource Allocation",
    "graduation_date": "Aug 2011",
    "img": "../assets/barna.png",
    "website": "https://barnasaha.net/",

  },
  {
    "name": "Jian Li",
    "bio":"IIIS, Tsinghua University.",
    "thesis": "Decision making under Uncertainty",
    "graduation_date": "Aug 2011",
    "img": "",
    "website": "http://people.iiis.tsinghua.edu.cn/~jianli/",

  },
  {
    "name": "Azarakhsh Malekian",
    "bio": "First job: Postdoc at Northwestern. Currently at U. Toronto.",
    "thesis": "Combinatorial problems in online advertising",
    "graduation_date": "Dec 2009",
    "img": "../assets/azar.jpg",
    "website": "https://sites.google.com/site/azarakhshm/",
  },
  {
    "name": "Srinivas Kashyap",
    "bio": "First job: Postdoc at IBM. Currently at Google.",
    "thesis": "Algorithms for data placement, reconfiguration and monitoring in storage networks",
    "graduation_date": "Aug 2007",
    "img": "../assets/google.webp",
    "website": "https://www.cs.umd.edu/community/alumnus/srinivas-kashyap",
  },
  {
    "name": "Julian Mestre",
    "bio": "Currently at U. Sydney.",
    "thesis": "Primal-Dual Algorithms for Combinatorial Optimization Problems",
    "graduation_date": "Aug 2007",
    "img": "../assets/julian.jpg",
    "website": "https://www.sydney.edu.au/engineering/about/our-people/academic-staff/julian-mestre.html"  
  },
  {
    "name": "Justin Wan",
    "bio": "Currently at Google.",
    "thesis": "Algorithms for Data Dissemination and Collection",
    "graduation_date": "May 2005",
    "img": "../assets/justin.jpg",
    "website": "http://www.cs.umd.edu/~ycwan/",
  },
  {
    "name": "Yoo Ah Kim",
    "bio": "Currently at NIH.",
    "thesis": "Algorithms for Data Migration",
    "graduation_date": "June 2005",
    "img": "../assets/yoo.jpg",
    "website": "https://www.linkedin.com/in/yoo-ah-kim-83281a6/",
  },
  {
    "name": "Michael Roberts",
    "thesis": "A preprocessor for shotgun assembly of large genomes",
    "graduation_date": "2003",
    "img": "../assets/maryland.jpg",
    "website": "https://www.linkedin.com/in/michael-roberts-81594a56/",
  },
  {
    "name": "Rajiv Gandhi",
    "bio": "Currently at Rutgers University (Camden). Winner of a Fulbright, and several teaching awards.",
    "thesis": "Broadcast Scheduling",
    "graduation_date": "May 2003",
    "img": "../assets/rajiv.jpg",
    "website": "http://www.crab.rutgers.edu/~rajivg/",
  },
  {
    "name": "Yoram Sussmann",
    "bio": "Currently at Iona College (New York).",
    "thesis": "Approximation Algorithms for Facility Location Problems",
    "graduation_date": "Feb 1999",
    "img": "../assets/iona.jpg",
    "website": "https://wiki.cs.umd.edu/theory/view/Alumni",

  },
  {
    "name": "Randeep Bhatia",
    "bio": "Currently at Bell Labs, NJ.",
    "thesis": "Approximation Algorithms for Scheduling Problems",
    "graduation_date": "Aug 1998",
    "img": "../assets/nokia.png",
    "website": "https://www.linkedin.com/in/randeep-bhatia-5939951/",
  },
];