export const awardData = [
  "CRA-E Undergraduate Research Mentoring Award (2020)",
  "Inaugural ESA Test of Time Award for work on Connected Dominating Sets (with S. Guha)",
  "Distinguished Scholar Teacher Award (UM) 2007-2008",
  "Google Research Award, Sep 2007",
  "PODS 2003 Best Newcomer Paper Award",
  "Dept Teaching Award, 2000-2001",
  "Lilly-CTE Teaching Fellowship, 1997",
  "Dean's Award for Excellence in Teaching, 1996",
  "NSF Faculty Development (CAREER) Award, 1995--1998",
  "NSF Research Initiation Award, 1993--1996",
  "Award for Outstanding Contributions to Seniors, Univ of Maryland, 1995",
  "Dept Teaching Award (Honorable Mention), 1994--1995",
  "Dept Teaching Award (Honorable Mention), 1993--1994",
  "Dept Teaching Award (Honorable Mention), 1992--1993",
  "IBM Graduate Fellowship, 1989--1990",
  "McMullen Graduate Fellowship, 1986--1987",
  "1st Rank, Computer Science and Engg, IIT-Kanpur, 1986",
  "All India Rank 8, 1982 IIT Entrance Examination",
  "Medal for top graduating student from La Martiniere College (Lucknow)",
  "First prize, story telling competition 2nd grade (Seetha Kingston House School)",
];
